3

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,19 +30,19 @@ jobs:
       # - name: Build Application and Docker Image
       #   run: ./mvnw -ntp -Pprod verify jib:dockerBuild
 
-      # - name: Verify Dockerfile
-      #   run: |
-      #     if [ -f Dockerfile ]; then
-      #       echo "Dockerfile found!"
-      #     else
-      #       echo "ERROR: Dockerfile not found!"
-      #       exit 1
-      #     fi
+      - name: Verify Dockerfile
+        run: |
+          if [ -f Dockerfile ]; then
+            echo "Dockerfile found!"
+          else
+            echo "ERROR: Dockerfile not found!"
+            exit 1
+          fi
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
+          aws-region: ${{ secrets.AWS_REGION }}
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
