3

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,20 +24,20 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Make mvnw Executable
-        run: chmod +x mvnw
+      # - name: Make mvnw Executable
+      #   run: chmod +x mvnw
 
-      - name: Build Application and Docker Image
-        run: ./mvnw -ntp -Pprod verify jib:dockerBuild
+      # - name: Build Application and Docker Image
+      #   run: ./mvnw -ntp -Pprod verify jib:dockerBuild
 
-      - name: Verify Dockerfile
-        run: |
-          if [ -f Dockerfile ]; then
-            echo "Dockerfile found!"
-          else
-            echo "ERROR: Dockerfile not found!"
-            exit 1
-          fi
+      # - name: Verify Dockerfile
+      #   run: |
+      #     if [ -f Dockerfile ]; then
+      #       echo "Dockerfile found!"
+      #     else
+      #       echo "ERROR: Dockerfile not found!"
+      #       exit 1
+      #     fi
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
